### ISSUE TITLE
申请使用授权

### ISSUE THREAD

**Issue by glzjin** [bash-c/pwn_repo#3]
Hi,

您好~我是 buuoj.cn 的站长。

看到您维护的这个项目觉得收集的题目非常好，想挂到我们这里的平台上，平台上的题目会保留链接指向您这里，您看可以吗？

谢谢，辛苦了~

glzjin

**Comment by bash-c** [comment]
我建议你直接从 ctftime 和  https://github.com/ctfs 找题目
我这里只存了一部分我自己做过的题目，并且现在也不怎么更新了。
从 ctftime 和  https://github.com/ctfs 找相关题目更全，并且链接更稳定（这个repo我已经有删除的想法了）

glzjin <notifications@github.com> 于2019年12月10日周二 下午7:54写道：

**Comment by glzjin** [comment]
谢谢，其实您这里收集得是最整洁的了，非常喜欢，太赞了👍
